name = "lifesync-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "lifesync-db"
database_id = "832c21f2-d209-42b7-8bbc-8b2ed95c13dd"

[[r2_buckets]]
binding = "R2"
bucket_name = "family-bucket"
